<a href="https://colab.research.google.com/github/Aditya2974/Machine-Learning/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [2]:
tf.__version__

'2.12.0'

In [8]:
# Tensorflow 2.0
df = pd.read_csv("Churn_Modelling.csv")
x = df.iloc[:,3:-1].values
y = df.iloc[:,-1].values

In [9]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [15]:
# We need to encode Country and Gender
# We can encode gender using Label Encoder as male = 1 female = 0
#Country using OneHotEncoder
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2]= le.fit_transform(x[:,2])
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers =[('encoder', OneHotEncoder() , [1])] , remainder = 'passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 1.0 ... 1 1 101348.88]
 [1.0 0.0 0.0 ... 0 1 112542.58]
 [1.0 0.0 1.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 1.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 1.0 ... 1 0 38190.78]]


In [19]:
# Feature Scaling
# Splitting the data into train and test set
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y, test_size = 0.2, random_state = 1)

In [22]:
#Feature Scaling for Deep Learning is very Important

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)
# print(x_train)
# print(x_test)

In [25]:
# Form a Neural Network
# Sequence of layers
model = tf.keras.models.Sequential()
#Input Layer and Hidden Layer
model.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))
# 2 hidden Layer
model.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))
#Output Layer
# Sigmoid as the output is 0 or 1
model.add(tf.keras.layers.Dense(units = 1,activation = 'sigmoid'))

In [26]:
#Compilation of the model
model.compile(optimizer='adam',loss = 'binary_crossentropy',metrics=['accuracy'])

In [27]:
model.fit(x_train,y_train,batch_size = 32,epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.5843 - accuracy: 0.7675
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4705 - accuracy: 0.8049
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4359 - accuracy: 0.8121
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4181 - accuracy: 0.8195
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4027 - accuracy: 0.8278
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3879 - accuracy: 0.8419
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3761 - accuracy: 0.8480
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3680 - accuracy: 0.8518
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3627 - accuracy: 0.8530
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3590 - accura

In [32]:
y_pred = model.predict(x_test)
y_pred = (y_pred > 0.5)

print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1520   65]
 [ 210  205]]


0.8625